config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'

  get 'student/index'

  get 'teacher/index'

  get 'users/welcome'

  get 'users/signup'

  get 'teacher/message'
  get 'teacher/send_message'
  get 'student/send_teacher' ,:as => 'send_teacher'
  get 'users/login'
  get 'student/message_student' ,:as => 'message_student'

  get 'student/choice_title', :as => 'choice_title'
  get 'student/confirm_title', :as => 'confirm_title'
  get 'student/upload_design', :as => 'upload_design'
  get 'student/delete_upload' , :as => 'delete_upload'
  get 'users/download', :as => 'download'
  get 'student/message' ,:as => 'message'
  get 'teacher/check' ,:as => 'check'
  get 'teacher/delete', :as => 'delete'
  get 'teacher/modify', :as => 'modify'
  get 'teacher/score', :as => 'score'
  get '/teacher/modify_score'
  get 'student/get_score',:as => 'get_score'
  get 'teacher/score_eva'  , :as => 'score_eva'
  patch 'teacher/design_update' => 'teacher#design_update',:as => 'design'
  post 'upload' => 'student#upload'

  post 'teacher_upload' => 'teacher#teacher_upload'
  post '/student/message_student' => 'student#message_student'

  get 'teacher/add_title' => 'teacher#add_title', :as => 'add_title'
  root to: "users#login"
  get "login" => "users#login", :as => "login"
  get "signup" => "users#signup", :as => "signup"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"
  resources :users, :designs, :messages, only: [:create]

end

app/models/design.rb
class Design < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :designs
  has_secure_password
  before_create { generate_token(:token) }

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @all_title = Design.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find_by_token(cookies[:token]) if cookies[:token]
  end

  helper_method :current_user
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  def create
    @user = Design.new(design_params)
    @user.teacher = current_user.id
    if @user.save
      redirect_to '/teacher/index'
    else
      render :back
    end
  end



  private
  def design_params
    params.require(:design).permit!
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @user = Message.new(message_params)
    @user.from = current_user.id
    if @user.save
      redirect_to '/teacher/index'
    else
      render :back
    end
  end



  private
  def message_params
    params.require(:message).permit!
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :judge_role , except: [:delete_upload]
  require 'find'
  def judge_role
    if current_user.role == '老师'
      redirect_to :root
    end
  end

  def get_score
  @score = Design.find_by_user_id(current_user.id)
  end
  def index
    if Design.find_by_user_id(current_user.id)
      redirect_to '/student/upload_design'
    else
      @all_title = Design.all
    end

  end

  def message_student
      @user = Message.new(message_params)
      @user.from = current_user.id
      if @user.save
        redirect_to '/student/index'
      else
        render :back
      end
  end

  def message

      @message = Message.where(:to => current_user.id)

  end

  def choice_title
    @title = Design.find_by_id(params[:id])
  end

  def send_teacher
    @message = Message.new
    @teacher = Design.find_by_user_id(current_user.id).teacher
  end

  def confirm_title
    title = Design.find_by_id(params[:id])
    title.user_id = current_user.id
    title.save
    redirect_to '/student/index'
  end

  def upload_design
    list = []
    if (File.exist?('public/upload/'+ current_user.id.to_s))
    else
      Dir.mkdir('public/upload/'+ current_user.id.to_s)
    end
    Find.find('public/upload/'+ current_user.id.to_s) do |path|
      if File.file?(path)
        yield path if block_given?
        files = {}
        files['name'] = File.basename(path)
        files['path'] = path
        list << files
      end
    end
    @picture_list = list
  end

  def upload
    if (File.exist?('public/upload/'+ current_user.id.to_s))
    else
      Dir.mkdir('public/upload/'+ current_user.id.to_s)
    end
    uploaded_io = params[:upload]
    File.open(Rails.root.join('public', 'upload', current_user.id.to_s, uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    redirect_to :back
  end

  def delete_upload
    path_file = File.join(params[:path])
    object_file=File.new(path_file, "w+")
    object_file.close # 缺少这一步，会报“in `delete': Permission denied - f:/ruby/Test.txt (Errno::EACCES)”
    File.delete(path_file)
    redirect_to :back
  end



  private
  def message_params
    params.require(:message).permit!
  end

end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  before_action :judge_role
  # skip_before_action :judge_role, only: [:login, :logout ,:signup,:create_login_session]
  def judge_role
    if current_user.role == '学生'
      redirect_to :root
    end
  end
  def score
  @score = Design.find_by_id(params[:id])
  end
  def modify_score
    @score = Design.find_by_id(params[:id])
    @score.score = params[:score]
    @score.save
    redirect_to '/teacher/score_eva'
  end
  def score_eva
    @all_title = Design.where(:teacher => current_user.id)
  end
  def index
    @all_title = Design.where(:teacher => current_user.id)
  end

  def modify
  @title = Design.find_by_id(params[:id])
  end

  def design_update
    @title = Design.find_by_id(params[:format])
    @title.title = params['design']['title']
    @title.demand = params['design']['demand']
    @title.save
    redirect_to '/teacher/index'
  end

  def delete
    Design.find_by_id(params[:id]).delete
    redirect_to :back
  end

  def add_title
    @title = Design.new
  end

  def message
    @message = Message.where(:to => current_user.id)
  end

  def send_message
    @message = Message.new
  end

  def check
    list = []
    if (File.exist?('public/upload/'+ Design.find_by_id(params[:id]).user_id.to_s))
    else
      Dir.mkdir('public/upload/'+ Design.find_by_id(params[:id]).user_id.to_s)
    end
    Find.find('public/upload/'+ Design.find_by_id(params[:id]).user_id.to_s) do |path|
      if File.file?(path)
        yield path if block_given?
        files = {}
        files['name'] = File.basename(path)
        files['path'] = path
        list << files
      end
    end
    @picture_list = list
  end

  def teacher_upload
    if (File.exist?('public/upload/'+ Design.find_by_id(params[:id]).user_id.to_s))
    else
      Dir.mkdir('public/upload/'+ Design.find_by_id(params[:id]).user_id.to_s)
    end
    uploaded_io = params[:upload]
    File.open(Rails.root.join('public', 'upload', Design.find_by_id(params[:id]).user_id.to_s, uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    redirect_to :back

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def welcome
  end


  def signup
    @user = User.new
  end

  def login
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # cookies.permanent[:token] = @user.token
      redirect_to :root
    else
      render :signup
    end
  end

  def logout
    cookies.delete(:token)
    redirect_to root_url
  end

  def create_login_session
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      cookies.permanent[:token] = user.token
      if user.role == '老师'
        redirect_to '/teacher/index'
      else
        if user.role == '学生'
          redirect_to '/student/index'
        else
          redirect_to '/admin/index'
        end
      end
    else
      redirect_to :login
    end
  end

  def download
    io = File.open(params[:path])
    io.binmode
    send_data(io.read, :filename => params[:name], :disposition => 'attachment')
  end

  private
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<div class="teacher_page_head"><h1>已设课题</h1></div>
<table class="topic">
  <tr>
    <th>
      题目
    </th>
    <th>需求</th>
    <th>老师</th>
    <th>学生</th>
    <th>删除课题</th>
  </tr>
  <%- @all_title.each do |p| %>
      <tr>
        <td>    <%= p.title %></td>
        <td><%= p.demand %></td>
        <td><%= User.find_by_id(p.teacher.to_i).name %></td>
        <% if p.user_id == nil %>
            <td></td>

        <% else %>
            <td><%= p.user.name %></td>
        <% end %>
        <td><%= link_to '删除', delete_path(:id => p.id) %></td>
      </tr>

  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BisheSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header' %>

<%= yield %>
</body>
</html>

app/views/shared/_header.html.erb
<div class="header">
  <!--<img src="../assets/a.jpg">-->
  <div class="container clearfix">
    <a class="header-logo-wordmark" href="/">
      HOME
    </a>
    <ul id="user-links">
      <% if current_user %>
          <li><%= link_to current_user.name, '#' %></li>
          <li><%= link_to "退出", logout_path, method: "delete" %></li>
          <% if current_user.role == '老师' %>
              <li><%= link_to '站内信', teacher_message_path %></li>
            <% else %>
              <li><%= link_to '站内信', message_path %></li>
    <% end %>

      <% else %>
          <li><%= link_to "注册", signup_path %></li>
          <li><%= link_to "登录", login_path %></li>

      <% end %>    </ul>
  </div>
</div>

app/views/student/choice_title.html.erb
<div class="landing"><h1>选择题目</h1></div>
<div class="choose_topic"><h3>题目</h3>
<%= @title.title %>
<h4>需求</h4>
<%= @title.demand %>
<h4>老师</h4>
<%= User.find_by_id(@title.teacher.to_i).name %>
<%= link_to '确认选择？选择后将无法修改，请确定' , confirm_title_path(:id=>@title.id) %>
</div>

app/views/student/get_score.html.erb
<div class="teacher_page_head"><h1>成绩</h1></div>

<table class="topic">
  <tr>
    <th>题目</th>
    <th>老师</th>
    <th>成绩</th>
    <th></th>
  </tr>
  <tr>
    <td>    <%= @score.title %></td>
    <td><%= User.find_by_id(@score.teacher.to_i).name %></td>
    <td><%= @score.score %></td>
  </tr>
</table>

app/views/student/index.html.erb
<div class="landing"><h1>已设课题</h1></div>
<table class="topic">
  <tr>
    <th id="a">
      题目
    </th>
    <th id="b">需求</th>
    <th id="c">老师</th>
    <th id="d">选题人</th>
  </tr>
  <%- @all_title.each do |p| %>
      <tr>
        <td>    <%= p.title %></td>
        <td><%= p.demand %></td>
        <td><%= User.find_by_id(p.teacher.to_i).name %></td>
        <% if (p.user_id != nil) %>
            <td><%=  p.user.name %></td>
        <% else %>
            <td><%= link_to '选题', choice_title_path(:id=>p.id) %></td>
        <% end %>
      </tr>

  <% end %>
</table>

app/views/student/message.erb
<h1>收到站内信</h1>

<%- @message.each do |p| %>
      <p><%= p.messages %> <%= link_to '回信' ,send_teacher_path %></p>

<% end %>

app/views/student/send_teacher.erb
<h1>发送站内信</h1>
<div class="single-form-container">
  <%= form_for @message, url: message_student_path do |f| %>
      <div class="boxed-group">
        <div class="boxed-group-inner">
          <dl class="form">
            <dt><%= f.label :message %></dt>
            <dd><%= f.text_area :messages  %></dd>
            <dd><%= f.text_field :to ,:value => @teacher ,:style => 'display:none' %></dd>
          </dl>
          <p class="stand_inside_letter_send"><%= f.submit "确定发送", :class => "button primary" %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/student/upload_design.html.erb
<div class="landing"><h1>上传文件</h1></div>
<div class="stand_inside_letter"><%= link_to '查看成绩' ,get_score_path  %></div>
<div class="stand_inside_letter"><%= link_to '向老师发送站内信' ,send_teacher_path  %></div>
<div class="upload"><%= form_tag({action: :upload}, multipart: true) do %>
<%= file_field_tag 'upload'  %>
<button>上传</button>
<% end %></div>

<div class="paper_download"><% for i in @picture_list %>
<%= i['name'] %>
    <%= link_to '下载' , download_path(:path => i['path'],:name=>i['name'])  %>
    <%= link_to '删除', delete_upload_path(:path => i['pa th']) %>
<% end %></div>

app/views/teacher/add_title.html.erb
<h1>添加题目</h1>
<div class="single-form-container">
  <%= form_for @title do |f| %>
      <div class="boxed-group">
        <div class="boxed-group-inner">
          <dl class="form">
            <dt><%= f.label :title %></dt>
            <dd><%= f.text_field :title %></dd>
          </dl>
          <dl class="form">
            <dt> <%= f.label :demand %></dt>
            <dd> <%= f.text_area :demand %> </dd>
          </dl>
          <p class="add_subject"><%= f.submit "确定添加", :class => "button primary" %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/teacher/check.erb
<h1>上传文件</h1>
<%= form_tag({action: :teacher_upload}, multipart: true) do %>
    <%= file_field_tag 'upload'  %>
    <%= text_area_tag 'id',params[:id],:style => 'display:none' %>
    <button>上传</button>
<% end %>

<% for i in @picture_list %>
    <%= i['name'] %>
    <%= link_to '下载' , download_path(:path => i['path'],:name=>i['name'])  %>
    <%= link_to '删除', delete_upload_path(:path => i['path']) %>
<% end %>

app/views/teacher/index.html.erb
<div class="teacher_page_head"><h1>已设课题</h1></div>
<div class="add_title"><%= link_to '添加题目', add_title_path %></div>
<div class="add_title"><%= link_to '成绩评定', score_eva_path %></div>

<table class="topic">
  <tr>
    <th>
      题目
    </th>
    <th>需求</th>
    <th>学生姓名</th>
    <th>查看完成情况</th>
    <th>发送站内信</th>
    <th>删除课题</th>
    <th>修改课题</th>
  </tr>
  <%- @all_title.each do |p| %>
      <tr>
        <td>    <%= p.title %></td>
        <td><%= p.demand %></td>

        <% if p.user_id == nil %>
            <td></td>
            <td></td>
            <td></td>
        <% else %>
            <td><%= p.user.name %></td>
            <td><%= link_to '查看', check_path(:id => p.id) %></td>
            <td><%= link_to '发送', teacher_send_message_path(:id => p.user_id) %></td>
        <% end %>
        <td><%= link_to '删除', delete_path(:id => p.id) %></td>
        <td><%= link_to '修改', modify_path(:id => p.id) %></td>
      </tr>

  <% end %>
</table>

app/views/teacher/message.erb
<h1>收到站内信</h1>

<%- @message.each do |p| %>
    <p><%= p.messages %> <%= link_to '回信' ,teacher_send_message_path(:id=>p.from) %></p>

<% end %>

app/views/teacher/modify.html.erb
<h1>修改题目</h1>
<div class="single-form-container">
  <%= form_for @title do |f| %>
      <div class="boxed-group">
        <div class="boxed-group-inner">
          <dl class="form">
            <dt><%= f.label :title %></dt>
            <dd><%= f.text_field :title %></dd>
          </dl>
          <dl class="form">
            <dt> <%= f.label :demand %></dt>
            <dd> <%= f.text_area :demand %> </dd>
          </dl>
          <p class="add_subject"><%= f.submit "确定修改", :class => "button primary" %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/teacher/score.html.erb
<div class="teacher_page_head"><h1>已设课题</h1></div>

<table class="topic">
  <tr>
    <th>题目</th>
    <th>学生名称</th>
    <th>成绩</th>
    <th></th>
  </tr>
      <tr>
        <td>    <%= @score.title %></td>
        <td><%= @score.user.name %></td>
        <td><input id="score" maxlength=2 onkeypress="var k=event.keyCode; return k>=48&&k<=57"
                   onpaste="return !clipboardData.getData('text').match(/\D/)"
                   ondragenter="return false"></td>
        <td><button onclick="score()">确定</button></td>
      </tr>
<input id="id" value= <%= @score.id %> style="display:none" >
</table>

app/views/teacher/score_eva.html.erb
<div class="teacher_page_head"><h1>已设课题</h1></div>

<table class="topic">
  <tr>
    <th>题目</th>
    <th>学生名称</th>
    <th>成绩评定</th>
  </tr>
  <%- @all_title.each do |p| %>
      <tr>

        <% if p.user_id == nil %>
            <td></td>
            <td></td>
        <% else %>
            <td>    <%= p.title %></td>
            <td><%= p.user.name %></td>
        <% end %>
        <% if p.score == nil %>
            <td><%= link_to '成绩评定', score_path(:id => p.id) %></td>

        <% else %>
            <td><%= p.score %></td>

        <% end %>
      </tr>

  <% end %>
</table>

app/views/teacher/send_message.erb
<h1>发送站内信</h1>
<div class="single-form-container">
  <%= form_for @message do |f| %>
      <div class="boxed-group">
        <div class="boxed-group-inner">
          <dl class="form">
            <dt><%= f.label :message %></dt>
            <dd><%= f.text_area :messages  %></dd>
            <dd><%= f.text_field :to ,:value => params[:id] ,:style=>'display:none' %></dd>
          </dl>
          <p><%= f.submit "确定发送", :class => "button primary" %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/users/login.html.erb
<div class="single-form-container">
  <div class="boxed-group" id="login">
     <div class="landing">
      <h1>登录</h1>
     </div>
    <div class="boxed-group-inner">
      <%= form_tag "/create_login_session" do %>
          <dl class="form">
            <dt>
              <%= label_tag "用户名" %>
            </dt>
            <dd class="user_name_box">
              <%= text_field_tag :name, params[:name] %>
            </dd>
          </dl>
          <dl class="form">
            <dt>
              <%= label_tag "密码" %>
            </dt>
            <dd class="user_name_box">
              <%= password_field_tag :password, params[:password] %>
            </dd>
          </dl>
          <p class="landing_bnt"> <%= submit_tag "登录", :class => "button primary" %> </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/signup.html.erb
<div class="single-form-container">
  <%= form_for @user do |f| %>
      <div class="boxed-group">
        <div class="landing"><h1>注册</h1></div>
        <div class="boxed-group-inner">
          <dl class="form">
            <dt><%= f.label :姓名 %></dt>
            <dd><%= f.text_field :name %></dd>
          </dl>
          <dl class="form">
            <dt> <%= f.label :学号 %></dt>
            <dd> <%= f.text_field :student_num %> </dd>
          </dl>
          <dl class="form">
            <dt> <%= f.label :密码 %> </dt>
            <dd> <%= f.password_field :password %> </dd>
          </dl>
          <dl class="form">
            <dt> <%= f.label :确认密码 %> </dt>
            <dd> <%= f.password_field :password_confirmation %> </dd>
          </dl>
          <dl class="form">
            <dt> <%= f.label :角色 %> </dt>
            <dd><%= f.select :role ,['学生','老师'] %></dd>
          </dl>
          <p class="landing_bnt"><%= f.submit "注册", :class => "button primary" %></p>
        </div>
      </div>
  <% end %>
</div>